version: '3'

services:

  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    volumes:
      - ./data:/data

  web:
    build: .
    ports:
      - 5000:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/data