name: learn-github-actions
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
     
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
           python-version: "3.7"
           
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      
      - name: Set Pythonpath
        run: |
          export PYTHONPATH="$PWD/src"
          echo $PYTHONPATH
      
      
      - name: Run pytest 
        run: python -m pytest
            
            
            
            
            
            